version: "2"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/myapp"
    links:
      - "db"
  db:
    image: "postgres:9.5.1"
    volumes:
      - "data:/var/lib/postgresql/data"
volumes:
  data: {}
